import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Read the DynamicCityRoute.tsx file
const filePath = path.join(__dirname, 'client/src/components/DynamicCityRoute.tsx');
let content = fs.readFileSync(filePath, 'utf-8');

// Function to convert kebab-case to PascalCase
function kebabToPascal(str) {
  return str.split('-').map(word => 
    word.charAt(0).toUpperCase() + word.slice(1)
  ).join('');
}

// List of all city keys and their PascalCase component names
const cityMappings = {
  'aarhus': 'Aarhus',
  'accra': 'Accra',
  'addis-ababa': 'AddisAbaba',
  'adelaide': 'Adelaide',
  'ahmedabad': 'Ahmedabad',
  'albuquerque': 'Albuquerque',
  'algiers': 'Algiers',
  'alice-springs': 'AliceSprings',
  'antwerp': 'Antwerp',
  'arequipa': 'Arequipa',
  'asuncin': 'Asuncin',
  'asuncion': 'Asuncion',
  'auckland': 'Auckland',
  'austin': 'Austin',
  'bandung': 'Bandung',
  'barranquilla': 'Barranquilla',
  'belgrade': 'Belgrade',
  'belo-horizonte': 'BeloHorizonte',
  'bergen': 'Bergen',
  'bilbao': 'Bilbao',
  'bologna': 'Bologna',
  'bordeaux': 'Bordeaux',
  'bratislava': 'Bratislava',
  'brisbane': 'Brisbane',
  'brno': 'Brno',
  'broome': 'Broome',
  'bucharest': 'Bucharest',
  'busan': 'Busan',
  'cairns': 'Cairns',
  'cairo': 'Cairo',
  'calgary': 'Calgary',
  'cali': 'Cali',
  'cape-town': 'CapeTown',
  'cartagena': 'Cartagena',
  'casablanca': 'Casablanca',
  'cebu': 'Cebu',
  'charleston': 'Charleston',
  'chiang-mai': 'ChiangMai',
  'christchurch': 'Christchurch',
  'colombo': 'Colombo',
  'columbus': 'Columbus',
  'copenhagen': 'Copenhagen',
  'crdoba': 'Crdoba',
  'curitiba': 'Curitiba',
  'cusco': 'Cusco',
  'da-nang': 'DaNang',
  'dakar': 'Dakar',
  'dalat': 'Dalat',
  'dar-es-salaam': 'DarEsSalaam',
  'darwin': 'Darwin',
  'debrecen': 'Debrecen',
  'edmonton': 'Edmonton',
  'fukuoka': 'Fukuoka',
  'gaborone': 'Gaborone',
  'gdansk': 'Gdansk',
  'genoa': 'Genoa',
  'ghent': 'Ghent',
  'gold-coast': 'GoldCoast',
  'gothenburg': 'Gothenburg',
  'guadalajara': 'Guadalajara',
  'guatemala-city': 'GuatemalaCity',
  'guayaquil': 'Guayaquil',
  'halifax': 'Halifax',
  'hanoi': 'Hanoi',
  'harare': 'Harare',
  'havana': 'Havana',
  'helsinki': 'Helsinki',
  'hobart': 'Hobart',
  'hoi-an': 'HoiAn',
  'indianapolis': 'Indianapolis',
  'ipoh': 'Ipoh',
  'jaipur': 'Jaipur',
  'johannesburg': 'Johannesburg',
  'kampala': 'Kampala',
  'kansas-city': 'KansasCity',
  'kathmandu': 'Kathmandu',
  'kingston': 'Kingston',
  'krakow': 'Krakow',
  'la-paz': 'LaPaz',
  'ljubljana': 'Ljubljana',
  'luanda': 'Luanda',
  'luang-prabang': 'LuangPrabang',
  'lusaka': 'Lusaka',
  'lyon': 'Lyon',
  'malacca': 'Malacca',
  'malaga': 'Malaga',
  'male': 'Male',
  'malm': 'Malm',
  'manaus': 'Manaus',
  'maputo': 'Maputo',
  'maracaibo': 'Maracaibo',
  'marrakech': 'Marrakech',
  'marseille': 'Marseille',
  'medellin': 'Medellin',
  'milwaukee': 'Milwaukee',
  'montevideo': 'Montevideo',
  'nairobi': 'Nairobi',
  'nashville': 'Nashville',
  'new-orleans': 'NewOrleans',
  'new-york': 'NewYork',
  'nice': 'Nice',
  'nouma': 'Nouma',
  'oaxaca': 'Oaxaca',
  'oslo': 'Oslo',
  'ottawa': 'Ottawa',
  'palermo': 'Palermo',
  'panama-city': 'PanamaCity',
  'papeete': 'Papeete',
  'penang': 'Penang',
  'perth': 'Perth',
  'port-moresby': 'PortMoresby',
  'portland': 'Portland',
  'porto': 'Porto',
  'quebec-city': 'QuebecCity',
  'queenstown': 'Queenstown',
  'quito': 'Quito',
  'reykjavik': 'Reykjavik',
  'riga': 'Riga',
  'rosario': 'Rosario',
  'sacramento': 'Sacramento',
  'salt-lake-city': 'SaltLakeCity',
  'salvador': 'Salvador',
  'san-antonio': 'SanAntonio',
  'san-jose': 'SanJose',
  'san-juan': 'SanJuan',
  'savannah': 'Savannah',
  'seville': 'Seville',
  'siem-reap': 'SiemReap',
  'sofia': 'Sofia',
  'stockholm': 'Stockholm',
  'strasbourg': 'Strasbourg',
  'sucre': 'Sucre',
  'surabaya': 'Surabaya',
  'suva': 'Suva',
  'tallinn': 'Tallinn',
  'tampere': 'Tampere',
  'the-hague': 'TheHague',
  'thessaloniki': 'Thessaloniki',
  'tokyo': 'Tokyo',
  'tunis': 'Tunis',
  'turin': 'Turin',
  'utrecht': 'Utrecht',
  'valencia': 'Valencia',
  'valparaiso': 'Valparaiso',
  'victoria': 'Victoria',
  'vilnius': 'Vilnius',
  'warsaw': 'Warsaw',
  'wellington': 'Wellington',
  'windhoek': 'Windhoek',
  'winnipeg': 'Winnipeg',
  'yogyakarta': 'Yogyakarta',
  'zagreb': 'Zagreb',
  'zaragoza': 'Zaragoza',
  'dubai': 'Dubai'
};

// Replace all city imports with the createCityImport function
Object.keys(cityMappings).forEach(cityKey => {
  if (cityKey !== 'aarhus') { // Skip aarhus since it's already fixed
    const componentName = cityMappings[cityKey];
    const oldPattern = `'${cityKey}': () => import('../pages/cities/${componentName}'),`;
    const newPattern = `'${cityKey}': createCityImport('${componentName}', '../pages/cities/${componentName}'),`;
    content = content.replace(oldPattern, newPattern);
  }
});

// Write the updated content back
fs.writeFileSync(filePath, content);
console.log('✅ Fixed all dynamic imports in DynamicCityRoute.tsx');